# -*- coding: utf-8 -*-
"""Sutirtho_Banerjee_2.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1dIaVcHhC_T7wUDOZYIiNbCOtGxQVjVYE?usp=sharing
"""

num = 7
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    print(f"Factorial of {num} = {fact}")

