# -*- coding: utf-8 -*-
"""Sutirtho_Banerjee_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7pqBteNQr77Xi_7iyeQMgMCb7H0OCKY
"""

text = input("Enter a string (e.g., remember): ")

reversed_text = ""
for ch in text:
    reversed_text = ch + reversed_text

print("Reversed string:", reversed_text)



"""# New Section"""