# -*- coding: utf-8 -*-
"""Sutirtho_Banerjee_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7pqBteNQr77Xi_7iyeQMgMCb7H0OCKY
"""

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")



"""# New Section"""