# -*- coding: utf-8 -*-
"""Sutirtho_Banerjee_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnG3fokyFuQ5X1ABjlVDY2-y5OkBXz0d?usp=sharing
"""

text = input("Enter a string (e.g., remember): ")

reversed_text = ""
for ch in text:
    reversed_text = ch + reversed_text

print("Reversed string:", reversed_text)



"""# New Section"""
