# -*- coding: utf-8 -*-
"""Sutirtho_Banerjee_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7pqBteNQr77Xi_7iyeQMgMCb7H0OCKY
"""

n = 55
total = 0
for i in range(1, n + 1):
    total += i

average = total / n
print(f"Sum of first {n} natural numbers = {total}")
print(f"Average = {average}")